cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    CI_REGISTRY: registry.gitlab.com
    CI_REGISTRY_IMAGE: registry.gitlab.com/smith.zsolt/news-backend-nodejs
  script:
    - echo "$DEPLOY_DOCKER_PASSWORD" |  docker login -u $DEPLOY_DOCKER_USER $DEPLOY_DOCKER_HOST --password-stdin
    - docker build --pull -t "$DEPLOY_DOCKER_IMAGE_NAME" .
    - docker push "$DEPLOY_DOCKER_IMAGE_NAME"
  only:
    - master

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --update --no-cache openssh sshpass
    - sshpass -V
    - export SSHPASS=$DEPLOY_REMOTE_PASSWORD
    - sshpass -e ssh -oStrictHostKeyChecking=no $DEPLOY_REMOTE_USERNAME@$DEPLOY_REMOTE_HOST '$DEPLOY_REMOTE_SCRIPT'
  only:
    - master
