version: "3"
services:
  mongo:
    image: mongo:latest
    volumes:
      - .db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27018:27017
    command: mongod --smallfiles
