version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR=/data/db
    command: mongod --smallfiles
  web:
    image: node:8.12
    ports:
      - 8090:8090
      - 3000:3000
    volumes:
      - ./source/:/home/node/app
    depends_on:
      - mongo
    working_dir: /home/node/app/_webtest/
    command: "node webtest.js"
    environment:
      PORT: "8090"
      WAIT_HOSTS: "mongo:27017"
      MONGOSERVER: "mongodb://mongo:27017/itcrowd"
      ALLOWORIGIN: "*"
      TWITTERCONSUMERKEY: "hNkkEwqeQsogsaRtsaWJbOtLI"
      TWITTERCONSUMERSECRET: "V2zd1oYo9wKcrgPpNr2TUDuUYTfQTWSAGPhJDaOYCc4Ja6D023"
      TWITTERACCESSTOKENKEY: "14412478-AL9CdP8hMTrnRIDcE0DBKFC7oMQLVbuTNYPg8MqHy"
      TWITTERACCESSTOKENSECRET: "sTzOnYbMjXSGVXFpKgwWUjT92wGW6Mkv1HOGrntsHnSHO"
      TWITTERSCREENNAME: "smithzsolt"
      ROOT_PATH: "/home/node/app"
      DEFAULT_IMAGE: "/twitter/image/default.jpg"
      IMAGE_STORE: "/_public/images"
      TWITTEREXCEPTION: "[\"1068042833796493300\",\"1057153873620725800\",\"1059328690247688200\"]"