version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - .db:/data/db
    command: mongod --smallfiles
  backend:
    image: itcrowd-server:latest
    ports:
      - 8080:8080
      - 8081:8081
      - 3000:3000
    volumes:
      - .backend:/home/node/app/_public/
    depends_on:
      - mongo
    environment:
      PORT: "8080"
      PORT_SSR: "8081"
      WAIT_HOSTS: "mongo:27017"
      MONGOSERVER: "mongodb://mongo:27017/itcrowd"
      MONGODATABASE: "itcrowd"
      SITEMAP_DOMAIN: "http://itcrowd.hu/"
      ALLOWORIGIN: "*"
      TWITTERCONSUMERKEY: "."
      TWITTERCONSUMERSECRET: "."
      TWITTERACCESSTOKENKEY: "."
      TWITTERACCESSTOKENSECRET: "."
      TWITTERSCREENNAME: "smithzsolt"
      ROOT_PATH: "/home/node/app"
      DEFAULT_IMAGE: "/twitter/image/default.jpg"
      IMAGE_STORE: "/_public/images"
      READ_COUNT: "190"
      IMAGE_SIZES: "[{\"name\": \"size1\",\"width\": 614},{\"name\": \"size2\",\"width\": 760}]"
      TWITTEREXCEPTION: "[\"1068042833796493300\",\"1057153873620725800\",\"1059328690247688200\"]"
