version: "3"
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
          - .data/db:/data/db
    ports:
      - 27018:27017
    command: mongod --smallfiles
        
